# Generated by Django 2.2.3 on 2019-07-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of technology')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('contennt', models.TextField(verbose_name='Content')),
                ('sort', models.IntegerField(default=0, unique=True, verbose_name='Sort field')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology', to='scraps.Technology')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['sort'],
            },
        ),
    ]
