# Generated by Django 2.2.3 on 2019-07-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologis'},
        ),
    ]
