# Generated by Django 2.2.3 on 2019-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0003_technology_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='l_name',
            field=models.CharField(max_length=255, verbose_name='Link name of technology(JavaScript=js)'),
        ),
    ]
