# Generated by Django 2.2.3 on 2019-07-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0004_auto_20190724_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='l_name',
            new_name='link_name',
        ),
    ]
