# Generated by Django 2.2.3 on 2019-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0005_auto_20190724_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='contennt',
            new_name='content',
        ),
    ]
