# Generated by Django 2.2.3 on 2019-07-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0006_auto_20190724_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='sort',
        ),
    ]
