# Generated by Django 2.2.3 on 2019-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0007_auto_20190724_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='<pre><code class="language-php"></code></pre>', verbose_name='Content'),
        ),
    ]
