# Generated by Django 2.2.3 on 2019-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0008_auto_20190724_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(default='<pre data-enlighter-language="python"></pre>', verbose_name='Content'),
        ),
    ]
