# Generated by Django 2.2.3 on 2019-07-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0009_auto_20190731_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
