# Generated by Django 2.2.3 on 2019-08-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0011_auto_20190804_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
